import Head from "next/head";
import Image from "next/image";
import Header from "../Components/Header";
import Portfolio from "../Components/Portfolio";

export default function Home() {
  return (
    <div className="font-primary">
      <Head>
        <title>Home | Tony ibrahim</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <header>
        <Header />
      </header>
      {/* Body */}
      <main>
        <Portfolio />
      </main>
      {/* Footer */}
      <footer></footer>
    </div>
  );
}
